'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ASTM_Test_Tool.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Received &apos;ENQ&apos;.
        '''</summary>
        Friend ReadOnly Property str101() As String
            Get
                Return ResourceManager.GetString("str101", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sending &apos;ACK&apos;.
        '''</summary>
        Friend ReadOnly Property str102() As String
            Get
                Return ResourceManager.GetString("str102", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Waiting for frame.
        '''</summary>
        Friend ReadOnly Property str103() As String
            Get
                Return ResourceManager.GetString("str103", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Received frame:  .
        '''</summary>
        Friend ReadOnly Property str104() As String
            Get
                Return ResourceManager.GetString("str104", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Parsing frame.
        '''</summary>
        Friend ReadOnly Property str105() As String
            Get
                Return ResourceManager.GetString("str105", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sending &apos;NAK&apos;.
        '''</summary>
        Friend ReadOnly Property str106() As String
            Get
                Return ResourceManager.GetString("str106", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Received &apos;EOT&apos;.
        '''</summary>
        Friend ReadOnly Property str107() As String
            Get
                Return ResourceManager.GetString("str107", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Idle.
        '''</summary>
        Friend ReadOnly Property str108() As String
            Get
                Return ResourceManager.GetString("str108", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Calculated checksum = .
        '''</summary>
        Friend ReadOnly Property str109() As String
            Get
                Return ResourceManager.GetString("str109", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reported checksum = .
        '''</summary>
        Friend ReadOnly Property str110() As String
            Get
                Return ResourceManager.GetString("str110", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Parsing record.
        '''</summary>
        Friend ReadOnly Property str111() As String
            Get
                Return ResourceManager.GetString("str111", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Starting state machine.
        '''</summary>
        Friend ReadOnly Property str112() As String
            Get
                Return ResourceManager.GetString("str112", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stopping state machine.
        '''</summary>
        Friend ReadOnly Property str113() As String
            Get
                Return ResourceManager.GetString("str113", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Building record.
        '''</summary>
        Friend ReadOnly Property str114() As String
            Get
                Return ResourceManager.GetString("str114", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Building frame.
        '''</summary>
        Friend ReadOnly Property str115() As String
            Get
                Return ResourceManager.GetString("str115", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sending &apos;ENQ&apos;.
        '''</summary>
        Friend ReadOnly Property str116() As String
            Get
                Return ResourceManager.GetString("str116", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Waiting for response.
        '''</summary>
        Friend ReadOnly Property str117() As String
            Get
                Return ResourceManager.GetString("str117", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Received &apos;ACK&apos;.
        '''</summary>
        Friend ReadOnly Property str118() As String
            Get
                Return ResourceManager.GetString("str118", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sending frame:  .
        '''</summary>
        Friend ReadOnly Property str119() As String
            Get
                Return ResourceManager.GetString("str119", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Received &apos;NAK&apos;.
        '''</summary>
        Friend ReadOnly Property str120() As String
            Get
                Return ResourceManager.GetString("str120", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sending &apos;EOT&apos;.
        '''</summary>
        Friend ReadOnly Property str121() As String
            Get
                Return ResourceManager.GetString("str121", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Piccolo busy.
        '''</summary>
        Friend ReadOnly Property str122() As String
            Get
                Return ResourceManager.GetString("str122", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sending frame again.
        '''</summary>
        Friend ReadOnly Property str123() As String
            Get
                Return ResourceManager.GetString("str123", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No more retries allowed.
        '''</summary>
        Friend ReadOnly Property str124() As String
            Get
                Return ResourceManager.GetString("str124", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Transmitting sequence:  .
        '''</summary>
        Friend ReadOnly Property str125() As String
            Get
                Return ResourceManager.GetString("str125", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Timeout waiting for Piccolo.
        '''</summary>
        Friend ReadOnly Property str201() As String
            Get
                Return ResourceManager.GetString("str201", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Frame error.
        '''</summary>
        Friend ReadOnly Property str202() As String
            Get
                Return ResourceManager.GetString("str202", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The database did not return any records.
        '''</summary>
        Friend ReadOnly Property str203() As String
            Get
                Return ResourceManager.GetString("str203", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No more fields for record.
        '''</summary>
        Friend ReadOnly Property str204() As String
            Get
                Return ResourceManager.GetString("str204", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Transmission field delimiter cannot be left blank!.
        '''</summary>
        Friend ReadOnly Property str205() As String
            Get
                Return ResourceManager.GetString("str205", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
